[package]
name = "hash_test"
version = "0.1.0"
edition = "2021"

[dependencies]
fmt = "0.1.0"
hex = "0.4.3"
ic-ledger-types = "0.11.0"
serde = "1.0.202"
serde_bytes = "0.11.14"
serde_cbor = "0.11.2"
sha2 = "0.10.8"
